#version 460 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D img_output;
layout (std140, binding = 1) uniform info {
    float time;
    int width;
    int height;
};

#define MAX_LEVEL 10
#define MAX_NB_CHARTS 4

#define NODE_FLAG_ACTIVE (1u << 0)
#define NODE_FLAG_LEAF (1u << 1)

struct octree_node {
    uint flags;
    uint level;

    uint chart_idx;
    float x, y, z;
    float dim;

    int root;
    int parent;
    int first_child;

    float value;
    float gradient[3];
};

layout (std430, binding = 0) buffer octree {
    uint nb_roots;
    octree_node nodes[];
};

#define OCTREE_DIM 8.0

vec3 hsv2rgb(vec3 c) {
    vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}

#define M_PI 3.14159265359
#define M_2PI 6.28318530718

float atan2(float y, float x) {
    return mod(atan(y, x), M_2PI);
}

float proj_radius(vec3 p, vec3 c) {
    return length(p.xz - c.xz);
}

float circle_dist(vec3 p, vec3 c, float r) {
    p = p - c;

    float D = length(p.xz);
    vec2 diff = vec2(D - r, p.y);
    
    return length(diff);
}

int convert_0(vec3 p_in, out vec3 p_out) {
    if (!(p_in.y > 0.25f || p_in.y < -0.25f || (length(p_in.xz + vec2(2.0, 0.0)) > 1.0f && length(p_in.xz - vec2(2.0, 0.0)) > 1.0f))) {
        return 0;
    }
    
    p_out = p_in;
    return 1;
}

int convert_1(vec3 p_in, out vec3 p_out) {
    if (!((p_in.y > -1.0f && length(p_in.xz + vec2(2.0, 0.0)) < 1.0f)
        || (p_in.y < 1.0f && length(p_in.xz - vec2(2.0, 0.0)) < 1.0f)))
    {
        return 0;
    }

    p_out = p_in;
    if (p_in.y > 0.0) {
        p_out.x -= 2.0;
    } else {
        p_out.x += 2.0;
    }

    return 1;
}

int convert_2(vec3 p_in, out vec3 p_out) {
    if (!((p_in.y > -1.0f && length(p_in.xz - vec2(2.0, 0.0)) < 1.0f)
        || (p_in.y < 1.0f && length(p_in.xz + vec2(2.0, 0.0)) < 1.0f)))
    {
        return 0;
    }

    p_out = p_in;
    if (p_in.y > 0.0) {
        p_out.x += 2.0;
    } else {
        p_out.x -= 2.0;
    }

    return 1;
}

int convert_3(vec3 p_in, out vec3 p_out) {
    if (!(circle_dist(p_in, vec3(-2.0, 0.0, 0.0), 1.0) < 0.75 || circle_dist(p_in, vec3(2.0, 0.0, 0.0), 1.0) < 0.75)) {
        return 0;
    }

    float R = 1.0f;
    vec3 mouth_circle1 = vec3(-2.0, 0.0, 0.0);
    vec3 mouth_circle2 = vec3(2.0, 0.0, 0.0);

    float r1 = circle_dist(p_in, mouth_circle1, R);
    float r2 = circle_dist(p_in, mouth_circle2, R);

    float r = 0.0;
    vec3 mc = vec3(0.0);
    float theta_offset = 0.0;
    if (r1 < 0.75) {
        r = r1;
        mc = mouth_circle1;

        if (p_in.y < 0.0) {
            theta_offset = 2.0 * M_PI;
        }
    } else if (r2 < 0.75) {
        r = r2;
        mc = mouth_circle2;

        theta_offset = 2.0 * M_PI;
    } else {
        return 0;
    }

    float theta = atan2(p_in[1] - mc[1], proj_radius(p_in, mc) - R) + theta_offset;
    float phi = atan2(p_in[2] - mc[2], p_in[0] - mc[0]);

    p_out[0] = r;
    p_out[1] = theta / (8.0f * M_PI) - 0.25f;
    p_out[2] = phi / (4.0f * M_PI) - 0.25f;

    return 1;
}

float vertical_coord() {
#define Z_BOUNDS OCTREE_DIM

    float z = time / 1.0;
    z = z - floor(z / Z_BOUNDS) * Z_BOUNDS;
    z -= Z_BOUNDS / 2.0;

    return z;
}

float ninf2(vec2 v) {
    vec2 a = abs(v);

    return max(a.x, a.y);
}

float ninf3(vec3 v) {
    vec3 a = abs(v);

    return max(max(a.x, a.y), a.z);
}

bool is_inside_node(int node_idx, vec3 coords) {
    vec3 center = vec3(nodes[node_idx].x, nodes[node_idx].y, nodes[node_idx].z);
    float hdim = nodes[node_idx].dim / 2.0;

    return ninf3(coords - center) <= hdim;
}

int find_node(int root_idx, vec3 coords) {
    if (!is_inside_node(root_idx, coords)) {
        return -1;
    }

    int idx = root_idx;
    for (int i = 0; i <= MAX_LEVEL; ++i) {
        vec3 center = vec3(nodes[idx].x, nodes[idx].y, nodes[idx].z);

        if (bool(nodes[idx].flags & NODE_FLAG_LEAF)) {
            return idx;
        }

        ivec3 cmp = ivec3(greaterThanEqual(coords, center));
        int child_idx = cmp.x | (cmp.y << 1) | (cmp.z << 2);

        idx = nodes[idx].first_child + child_idx;
    }
}

vec4 draw_octree_slice(vec2 xy) {
    float z = vertical_coord();
    vec3 coords = vec3(xy.x, xy.y, z);

    int enabled_charts = 0;
    vec3 chart_coords[MAX_NB_CHARTS];
    
    enabled_charts |= convert_0(coords, chart_coords[0]);
    enabled_charts |= convert_1(coords, chart_coords[1]) << 1;
    enabled_charts |= convert_2(coords, chart_coords[2]) << 2;
    enabled_charts |= convert_3(coords, chart_coords[3]) << 3;

    vec4 res = vec4(0.5, 0.0, 0.0, 1.0);
    for (int i = 0; i < MAX_NB_CHARTS; ++i) {
        if (!bool((enabled_charts >> i) & 1)) {
            continue;
        }

        for (int root_idx = 0; root_idx < nb_roots; ++root_idx) {
            if (nodes[root_idx].chart_idx != i) {
                continue;
            }

            if (!is_inside_node(root_idx, chart_coords[i])) {   
                continue;
            }

            int idx = find_node(root_idx, chart_coords[i]);

            vec3 center = vec3(nodes[idx].x, nodes[idx].y, nodes[idx].z);
            float hdim = nodes[idx].dim / 2.0;
            float c = hdim - ninf2(chart_coords[i].xy - center.xy);

            if (!bool(nodes[idx].flags & NODE_FLAG_ACTIVE)) {
                continue;
            }

            if (c < 0.001 * nodes[root_idx].dim) {
                res = vec4(0.0, 0.0, 0.0, 1.0);
                continue;
            }

            float color_shift = float(i + 1);
            res = vec4(hsv2rgb(vec3(50.0 * color_shift / 355.0, 1.0, 1.0)), 1.0);
        }
    }

    return res;
}

void main() {
    ivec2 texture_size = imageSize(img_output);
	ivec2 texel_coord = ivec2(gl_GlobalInvocationID.xy);

    float aspect_ratio = float(width) / float(height);
    vec2 uv = (vec2(texel_coord) / texture_size * 2.0 - 1.0) * vec2(aspect_ratio, 1.0);

    vec2 plot = uv * OCTREE_DIM / 1.5;
    vec4 res_color = draw_octree_slice(plot);

    imageStore(img_output, texel_coord, res_color);
}