#version 460 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D img_output;
layout (std140, binding = 1) uniform info {
    float time;
    int width;
    int height;
};
layout (std140, binding = 2) uniform camera {
    vec3 cam_position;
    mat3 cam_rotation;
    float cam_fov;
    float cam_focal_length;
};

#define MAX_LEVEL 16

#define NODE_FLAG_ACTIVE (1 << 0)
#define NODE_FLAG_LEAF (1 << 1)

struct octree_node {
    uint flags;
    uint level;

    uint chart_idx;
    float x, y, z;
    float dim;

    int root;
    int parent;
    int first_child;

    float value;
    float gradient[3];
};

layout (std430, binding = 0) buffer octree {
    octree_node nodes[];
};

#define OCTREE_DIM 8.0

#define MAX_STEPS 1000
#define MAX_DISTANCE (OCTREE_DIM * 1.7)
#define MIN_SURFACE_DISTANCE 0.075

#define SQR(x) ((x) * (x))

bool is_oob(vec3 ro, vec3 p) {
    return length(p - ro) > MAX_DISTANCE;
}

vec3 get_bounding_sphere_color(vec3 rd) {
    float t = 1.0 - abs(sin(rd.y * 3.14 / 2.0));
    vec3 blue = vec3(216.0, 249.0, 255.0) / 255.0;

    return mix(vec3(1.0), blue, t);
}

vec3 checkerboard_color(vec3 p) {
    float checker = sign(sin(p.x * 4.0) * sin(p.z * 4.0));
    
    return mix(vec3(0.4), vec3(0.6), checker);
}

vec3 hsv2rgb(vec3 c) {
    vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}

float ninf3(vec3 v) {
    vec3 a = abs(v);

    return max(max(a.x, a.y), a.z);
}

bool is_inside_node(uint node_idx, vec3 coords) {
    vec3 center = vec3(nodes[node_idx].x, nodes[node_idx].y, nodes[node_idx].z);
    float hdim = nodes[node_idx].dim / 2.0;

    return ninf3(coords - center) <= hdim;
}

float calc_distance(vec3 p) {
    if (!is_inside_node(0, p)) {
        return MIN_SURFACE_DISTANCE;
    }

    int idx = 0;
    for (int i = 0; i <= MAX_LEVEL; ++i) {
        vec3 center = vec3(nodes[idx].x, nodes[idx].y, nodes[idx].z);

        if (bool(nodes[idx].flags & NODE_FLAG_LEAF)) {
            vec3 grad = vec3(nodes[idx].gradient[0], nodes[idx].gradient[1], nodes[idx].gradient[2]);
            float approx = nodes[idx].value + dot(grad, p - center);

            return approx;
        }

        ivec3 cmp = ivec3(greaterThanEqual(p, center));
        int child_idx = cmp.x | (cmp.y << 1) | (cmp.z << 2);

        idx = nodes[idx].first_child + child_idx;
    }
}

#define INT_STEP 0.075

vec4 do_step(vec3 p, vec3 rd, float d) {
    for (int i = 0; i < min(MAX_STEPS, int(floor(d / INT_STEP))); ++i) {
        p += rd * INT_STEP;
        if (ninf3(p) > OCTREE_DIM / 2.0) {
            return vec4(p, i);
        }
    }

    return vec4(p, MAX_STEPS);
}

float sdBoxFrame( vec3 p, vec3 b, float e )
{
       p = abs(p  )-b;
  vec3 q = abs(p+e)-e;
  return min(min(
      length(max(vec3(p.x,q.y,q.z),0.0))+min(max(p.x,max(q.y,q.z)),0.0),
      length(max(vec3(q.x,p.y,q.z),0.0))+min(max(q.x,max(p.y,q.z)),0.0)),
      length(max(vec3(q.x,q.y,p.z),0.0))+min(max(q.x,max(q.y,p.z)),0.0));
}

vec3 ray_march(vec3 ro, vec3 rd) {
    vec3 p = ro;

    int prev_steps = 0;
    for (int i = 0; i < MAX_STEPS; ++i) {
        float d = min(calc_distance(p), sdBoxFrame(p, vec3(OCTREE_DIM / 2.0), 0.01));
        if (d < MIN_SURFACE_DISTANCE) {
            return vec3(0.5, 0.0, 0.0);
        }

        vec4 tmp = do_step(p, rd, d);
        prev_steps += int(tmp.w);

        p = tmp.xyz;
        if (is_oob(ro, p)) {
            return get_bounding_sphere_color(rd);
            // return vec3(float(prev_steps) / MAX_STEPS / MAX_STEPS * 5.0, 0.0, 0.0);
        }
    }

    return get_bounding_sphere_color(rd);
}

void main() {
    ivec2 texture_size = imageSize(img_output);
	ivec2 texel_coord = ivec2(gl_GlobalInvocationID.xy);

    float aspect_ratio = float(width) / float(height);
    float fov = radians(cam_fov);
    vec2 uv = (vec2(texel_coord) / texture_size * 2.0 - 1.0) * vec2(aspect_ratio, 1.0) * tan(fov / 2);

    vec3 ro = cam_position;
    vec3 rd = cam_rotation * normalize(vec3(uv, cam_focal_length));

    vec3 color = ray_march(ro, rd);
    imageStore(img_output, texel_coord, vec4(color, 1.0));
}